site_name: Документация Open vAIR
dev_addr: 192.168.122.50:8001

#
#
#nav:
#  - Введение:
#      - Про Open vAIR: getting_started/index.md
#      - Установка и удаление: getting_started/install.md
#      - Патчирование/Обновление проекта: getting_started/update.md
#
#  - Контрибьюторам:
#      - Общий подход: contributors/general.md
#      - Тестирование: contributors/tests.md
#
#  - Спецификация модулей:
#      - Введение: reference/index.md
#      - volume:
#          - Описание модуля: reference/volume/specification.md
#          - Тесты: reference/volume/tests_specification.md
#
#  - Структура проекта:
#      - architecture/general_terms.md
#      - Общая Структура Модуля:
#          - architecture/general_module/introduction.md
#          - architecture/general_module/adapters.md
#          - architecture/general_module/domain.md
#          - architecture/general_module/entrypoints.md
#          - architecture/general_module/service_layer.md
#          - architecture/general_module/module_dir.md
#
#  - Инструкция для пользователя:
#      - Введение: user_guide/introduction.md
#      - Хранилища: user_guide/storages.md
#      - Виртуальные диски: user_guide/volume.md
#      - Образы: user_guide/image.md
#      - Блочные устройства: user_guide/block_devices.md
#      - Network: user_guide/network.md
#      - Виртуальные сети: user_guide/virtual_networks.md
#      - Виртуальные машины: user_guide/virtual_machines.md
#      - Управление пользователями: user_guide/user.md
#      - Dashboard: user_guide/dashboard.md
#      - Event Store: user_guide/event_store.md
#      - SNMP: user_guide/SNMP.md
#      - Sentry: user_guide/sentry.md
#      - Резервное копирование: user_guide/backup.md
#      - Уведомления: user_guide/notification.md
#      - Вложенная виртуализация: user_guide/nested_virtualization.md

nav:
  - Введение:
    - getting_started/index.md
    - getting_started/install.md
    - getting_started/update.md
  - Руководство пользователя:
      - Обзор: user_guide/index.md
      - Виртуальные машины: user_guide/virtual_machines.md
      - Виртуальные тома: user_guide/volume.md
      - Хранилища: user_guide/storages.md
      - Сеть: user_guide/network.md
      - SNMP: user_guide/SNMP.md
      - Backup: user_guide/backup.md
      - Block devices: user_guide/block_devices.md
      - Dashboard: user_guide/dashboard.md
      - Event Store: user_guide/event_store.md
      - Образы: user_guide/image.md
      - Nested Virtualization: user_guide/nested_virtualization.md
      - Notification: user_guide/notification.md
      - Sentry: user_guide/sentry.md
      - Пользователи: user_guide/user.md
      - Виртуальные сети: user_guide/virtual_networks.md
  - Справочник:
      - Обзор: reference/index.md
      - Модули:
          - Обзор: reference/modules/index.md
          - Виртуальные тома: reference/modules/volume.md
          - Шаблоны:
              Обзор: reference/modules/template/index.md
              Технические требования: reference/modules/template/tech_requirements.md
              Документация: reference/modules/template/specification.md
              Документация тестов: reference/modules/template/tests_specification.md
          # Добавь остальные спецификации модулей
      - API: reference/api.md
  - Вклад и разработка:
      - Обзор: contributors/index.md
      - Основное: contributors/general.md
      - Тесты: contributors/tests.md
  - Архитектура:
      - Обзор: architecture/index.md
      - Термины: architecture/general_terms.md
      - General Module:
          - Adapters: architecture/general_module/adapters.md
          - Domain: architecture/general_module/domain.md
          - Entrypoints: architecture/general_module/entrypoints.md
          - Введение: architecture/general_module/introduction.md
          - module_dir: architecture/general_module/module_dir.md
          - service_layer: architecture/general_module/service_layer.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

plugins:
  - glightbox

theme:
  name: material
  features:
    - header.autohide
    - navigation.tabs
    - navigation.instant
    - navigation.instant.progress
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Переключить на тёмную тему
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/white-balance-sunny
        name: Переключить на светлую тему
