site_name: Документация Open vAIR
dev_addr:

repo_url: https://github.com/Aerodisk/openvair
repo_name: Open vAIR на GitHub

plugins:
  - glightbox
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

theme:
  name: material
  logo: _assets/logo.png
  features:
    - header.autohide
    - navigation.tabs
    - navigation.instant
    - navigation.instant.progress
  palette:
    - scheme: default
      primary: "#1F4E79"
      accent: orange
      toggle:
        icon: material/weather-night
        name: Тёмная тема
    - scheme: slate
      primary: "#1F4E79"
      accent: white
      toggle:
        icon: material/white-balance-sunny
        name: Светлая тема
      font:
        text: Roboto
        code: Fira Mono
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Aerodisk/openvair
    - icon: fontawesome/brands/telegram
      link: https://t.me/Open_vAIR_AERODISK

      
nav:
  - Введение:
      - getting_started/index.md
      - getting_started/install.md
      - getting_started/update.md
      - getting_started/system_requirements.md
  - Руководство пользователя:
      - Обзор: user_guide/index.md
      - Виртуальные машины: user_guide/virtual_machines.md
      - Виртуальные тома: user_guide/volume.md
      - Хранилища: user_guide/storages.md
      - Сеть: user_guide/network.md
      - SNMP: user_guide/SNMP.md
      - Backup: user_guide/backup.md
      - Block devices: user_guide/block_devices.md
      - Dashboard: user_guide/dashboard.md
      - Event Store: user_guide/event_store.md
      - Образы: user_guide/image.md
      - Nested Virtualization: user_guide/nested_virtualization.md
      - Notification: user_guide/notification.md
      - Sentry: user_guide/sentry.md
      - Пользователи: user_guide/user.md
      - Виртуальные сети: user_guide/virtual_networks.md
      - Снапшоты: user_guide/snapshots.md
  - Справочник:
      - Обзор: reference/index.md
      - Модули:
          - Обзор: reference/modules/index.md
          - Виртуальные тома:
              - Обзор: reference/modules/volume/index.md
              - Технические требования: reference/modules/volume/tech_requirements.md
              - Документация: reference/modules/volume/specification.md
              - Документация тестов: reference/modules/volume/tests_specification.md
              - FAQ: reference/modules/volume/faq.md
          - Шаблоны:
              - Обзор: reference/modules/template/index.md
              - Технические требования: reference/modules/template/tech_requirements.md
              - Документация: reference/modules/template/specification.md
              - Документация тестов: reference/modules/template/tests_specification.md
              - FAQ: reference/modules/template/faq.md
          - Снапшоты:
              - Обзор: reference/modules/snapshots/index.md
              - Технические требования: reference/modules/snapshots/tech_requirements.md
              - Документация: reference/modules/snapshots/specification.md
              - FAQ: reference/modules/snapshots/faq.md
      - API: reference/api.md
  - Вклад и разработка:
      - Обзор: contributors/index.md
      - Основное: contributors/general.md
      - Тесты: contributors/tests.md
      - Документация:
          - Обзор: contributors/docs/index.md
          - FAQ по структуре документации: contributors/docs/structure_faq.md
          - Как оформлять документацию для существующего модуля: contributors/docs/howto.md
  - Архитектура:
      - Обзор: architecture/index.md
      - Термины: architecture/general_terms.md
      - General Module:
          - Обзор: architecture/general_module/index.md
          - Введение: architecture/general_module/introduction.md
          - Adapters: architecture/general_module/adapters.md
          - Domain: architecture/general_module/domain.md
          - Entrypoints: architecture/general_module/entrypoints.md
          - module_dir: architecture/general_module/module_dir.md
          - service_layer: architecture/general_module/service_layer.md
